streaming/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resource :streams, only: [:index, :create] do
    get 'stream', action: :stream, as: :my_stream
    get ':token', action: :watch, as: :watch
  end

  root 'streams#index'
end

streaming/app/models/stream.rb
class Stream < ApplicationRecord
  
  has_secure_token :token

  before_create do |stream|
    session = OpenTokClient.create_session
    stream.opentok_session_id = session.session_id
  end

  belongs_to :user
end

streaming/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :stream
end

streaming/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

streaming/app/controllers/streams_controller.rb
class StreamsController < ApplicationController

  before_action :authenticate_user!

  def index
    @stream = current_user.stream
  end

  def create
    current_user.stream.destroy if current_user.stream
    current_user.create_stream
    redirect_to my_stream_streams_path
  end

  def stream
    @stream = current_user.stream
    gon.opentok = opentok_data(@stream)
  end

  def watch
    @stream = Stream.find_by(token: params[:token])
    gon.opentok = opentok_data(@stream)
  end

  private

  def opentok_data(stream)
    token = OpenTokClient.generate_token(stream.opentok_session_id)
    { sessionId: stream.opentok_session_id, apiKey: Figaro.env.opentok_api_key, token: token }
  end
end

streaming/app/helpers/streams_helper.rb
module StreamsHelper
end

streaming/app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.erb

= link_to 'Create stream', streams_path, method: :post

streaming/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tokbox
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = Gon::Base.render_data
  %body
    = yield

streaming/app/views/streams/index.haml
%h1 Hello

%div
  = link_to 'Create stream', streams_path, method: :post

%div
  = link_to 'Sign out', destroy_user_session_path, method: :delete

streaming/app/views/streams/stream.haml
= javascript_include_tag "//static.opentok.com/webrtc/v2.2/js/TB.min.js"

- if current_user.id == @stream.user_id
  %p
    Link to your stream: 
    = link_to 'Click', watch_streams_path(token: @stream.token)

= link_to 'Back', root_path

.row
  #stream.col-md-6
  #publisher.col-md-6

streaming/app/views/streams/watch.haml
= javascript_include_tag "//static.opentok.com/webrtc/v2.2/js/TB.min.js"

%h1= "#{@stream.user.email}\'s stream"

.row
  #stream.col-md-6
  #publisher.col-md-6

streaming/app/views/users/stream.html.haml
= javascript_include_tag "//static.opentok.com/webrtc/v2.2/js/TB.min.js"
%h1 Your stream
#publisher
Link to your stream: #{link_to watch_url(@stream.user.id), watch_url(@stream.user.id)}

streaming/app/views/users/watch.html.haml
= javascript_include_tag "//static.opentok.com/webrtc/v2.2/js/TB.min.js"
%h1
  = @stream.user.email
  's stream
#stream